
global ff ffdir ffdatadir sfdir verbosity

verbosity = 1; % to control the ammount of output

if(isunix)
    %ff =  '/usr/local/bin/FreeFem++';   % on most systems, including the server AZTECA (UPS)
    ff = '/PRODCOM/Ubuntu16.04/freefem/3.55/gcc-5.4-mpich_3.2/bin/FreeFem++'; % on IMFT
    %Network
end

if(ismac)
    %ff =  '/usr/local/bin/FreeFem++'; % on most mac instalations
    ff = '/usr/local/ff++/openmpi-2.1/3.55/bin/FreeFem++-nw'; % on DF's macbookpro 
end
   
if(ispc)
    ff = 'launchff++'; % for windows systems
end

sfdir = '~/StabFem/SOURCES_MATLAB/'; % where to find the matlab drivers
ffdir = '~/StabFem/SOURCES_FREEFEM/'; % where to find the freefem scripts

addpath(sfdir);

ffdatadir = './WORK/'; % where the files generated by the freefem scripts will be stored
if(exist(ffdatadir)~=7&&exist(ffdatadir)~=5)
    mysystem(['mkdir ' ffdatadir]);
end

mysystem(['echo "// File automatically created by StabFem" > SF_Geom.edp']); 
% a file SF_Geom should be present, even if blank 